core_index:
    path:     /
    defaults: { _controller: CoreBundle:Front:index }


core_ajaxnature:
    path:     /ajaxnature
    defaults: { _controller: CoreBundle:Front:ajaxnature }
    requirements:
      _method: POST

core_searchEspece:
    path:     /rechercher
    defaults: { _controller: CoreBundle:Front:searchEspece }

core_searchFicheEspece:
    path:     /rechercher/{id}
    defaults: { _controller: CoreBundle:Front:searchFicheEspece }