core_index:
    path:     /
    defaults: { _controller: CoreBundle:Front:index }

core_autocompletion:
    path:     /autocompletion
    defaults: { _controller: CoreBundle:Front:autocompletion }
    requirements:
      _method: POST

core_searchEspece:
    path:     /recherche
    defaults: { _controller: CoreBundle:Front:searchEspece }

core_searchFicheEspece:
    path:     /rechercher/{id}
    defaults: { _controller: CoreBundle:Front:searchFicheEspece }

core_searchObservation:
    path:     /obs/{id}
    defaults: { _controller: CoreBundle:Front:searchObservation }

core_observation:
    path:     /observation
    defaults: { _controller: CoreBundle:Front:observation }
    requirements:
        _method: POST

core_association:
    path:     /association
    defaults: { _controller: CoreBundle:Front:association }

core_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: CoreBundle:Front:mentionsLegales }

core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Front:contact }

core_admin:
    path:     /admin
    defaults: { _controller: CoreBundle:Back:admin }