core_index:
    path:     /
    defaults: { _controller: CoreBundle:Front:index }

core_autocompletion:
    path:     /autocompletion
    defaults: { _controller: CoreBundle:Front:autocompletion }
    requirements:
      _method: POST

core_searchEspece:
    path:     /recherche
    defaults: { _controller: CoreBundle:Front:searchEspece }

core_searchObservation:
    path:     /obs/{id}
    defaults: { _controller: CoreBundle:Front:searchObservation }

core_observation:
    path:     /observation
    defaults: { _controller: CoreBundle:Front:observation }

core_liste:
    path:     /liste/{id}
    defaults: {_controller: CoreBundle:Front:liste }

core_saisie:
    path:     /saisie/{id}
    defaults: { _controller: CoreBundle:Front:saisie }

core_association:
    path:     /association
    defaults: { _controller: CoreBundle:Front:association }

core_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: CoreBundle:Front:mentionsLegales }

core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Front:contact }

core_admin:
    path:     /admin
    defaults: { _controller: CoreBundle:Back:admin }

core_valide_nat:
    path: /valide_nat/{id}
    defaults: { _controller:CoreBundle:Back:valideNat }
    requirements:
        id: \d+

core_refuse_nat:
    path: /refuse_nat/{id}
    defaults: { _controller:CoreBundle:Back:refuseNat }
    requirements:
        id: \d+

core_valide_obs:
    path: /valide_obs/{id}
    defaults: { _controller:CoreBundle:Back:valideObs }
    requirements:
        id: \d+

core_delete_obs:
    path: /delete_obs/{id}
    defaults: { _controller:CoreBundle:Back:deleteObs }
    requirements:
        id: \d+