Nao\CoreBundle\Entity\Espece:
    type: entity
    table: espece
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        regne:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: REGNE
        phylum:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: PHYLUM
        classe:
            type: string
            nullable: true
            length: 4
            options:
                fixed: false
            column: CLASSE
        ordre:
            type: string
            nullable: true
            length: 19
            options:
                fixed: false
            column: ORDRE
        famille:
            type: string
            nullable: true
            length: 17
            options:
                fixed: false
            column: FAMILLE
        cdNom:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_NOM
        cdTaxsup:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
            column: CD_TAXSUP
        cdSup:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
            column: CD_SUP
        cdRef:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_REF
        rang:
            type: string
            nullable: true
            length: 4
            options:
                fixed: false
            column: RANG
        lbNom:
            type: string
            nullable: true
            length: 47
            options:
                fixed: false
            column: LB_NOM
        lbAuteur:
            type: string
            nullable: true
            length: 73
            options:
                fixed: false
            column: LB_AUTEUR
        nomComplet:
            type: string
            nullable: true
            length: 86
            options:
                fixed: false
            column: NOM_COMPLET
        nomCompletHtml:
            type: string
            nullable: true
            length: 93
            options:
                fixed: false
            column: NOM_COMPLET_HTML
        nomValide:
            type: string
            nullable: true
            length: 86
            options:
                fixed: false
            column: NOM_VALIDE
        nomVern:
            type: string
            nullable: true
            length: 101
            options:
                fixed: false
            column: NOM_VERN
        nomVernEng:
            type: string
            nullable: true
            length: 122
            options:
                fixed: false
            column: NOM_VERN_ENG
        habitat:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: HABITAT
        fr:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: FR
        url:
            type: string
            nullable: true
            length: 42
            options:
                fixed: false
            column: URL
    lifecycleCallbacks: {  }
