<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{

	// Depuis un repository
	public function mase($id)
	{
		$query = $this->_em->createQuery('SELECT a.date, a.latitude, a.longitude, a.statut, u.id, u.username FROM CoreBundle:Observation a JOIN CoreBundle:User u WHERE a.espece = :id AND a.statut = 1 AND a.user = u.id');
	 	//$query->andWhere(u.id = a.user_id);
		$query->setParameter('id', $id);

		$results = $query->getArrayResult();

		return $results;
	}
	
	public function myFindBy()
	{
		
		$qb = $this
			->createQueryBuilder('o')
		;		

		$qb->where('o.statut = 0')
			->orderBy('o.date', 'DESC')
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
	
	

}
